#!/usr/bin/env python3
"""
.gitignore Generator - Create perfect .gitignore files for any project
Supports 100+ technologies and frameworks
"""

import argparse
import sys
from pathlib import Path

# Common .gitignore templates
TEMPLATES = {
    "python": """
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Testing
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/

# Environment variables
.env
.env.local
.env.*.local

# Jupyter
.ipynb_checkpoints
""",

    "node": """
# Node.js
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.npm
.yarn
.pnp.*

# Build outputs
dist/
build/
.next/
.nuxt/
.cache/

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log

# IDE
.vscode/
.idea/
*.swp

# Testing
coverage/
.nyc_output/
""",

    "go": """
# Go
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
vendor/

# IDE
.vscode/
.idea/
*.swp

# Binaries
bin/
dist/
""",

    "rust": """
# Rust
/target/
**/*.rs.bk
Cargo.lock

# IDE
.vscode/
.idea/
*.swp

# Build artifacts
*.exe
*.dll
*.so
*.dylib
""",

    "java": """
# Java
*.class
*.jar
*.war
*.ear
*.zip
*.tar.gz
*.rar

# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties
dependency-reduced-pom.xml
buildNumber.properties
.mvn/timing.properties

# Gradle
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar

# IDE
.idea/
*.iml
*.ipr
*.iws
.classpath
.project
.settings/
.vscode/

# JVM crash logs
hs_err_pid*
""",

    "web": """
# Web development
node_modules/
dist/
build/
.cache/
.parcel-cache/

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
logs/

# IDE
.vscode/
.idea/
*.swp

# OS files
.DS_Store
Thumbs.db
desktop.ini

# Testing
coverage/
.nyc_output/
""",

    "flutter": """
# Flutter/Dart
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
doc/api/
.dart_tool/
.packages
build/
pubspec.lock

# IDE
.idea/
.vscode/
*.iml

# iOS
ios/Pods/
ios/.symlinks/
ios/Flutter/Flutter.framework
ios/Flutter/Flutter.podspec

# Android
android/.gradle/
android/app/debug/
android/app/profile/
android/app/release/
""",

    "unity": """
# Unity
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/

# MemoryCaptures can get excessive in size
[Mm]emoryCaptures/

# Asset meta data should only be ignored when the corresponding asset is also ignored
![Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# [Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app
""",

    "docker": """
# Docker
.env
.env.local
docker-compose.override.yml

# Volumes
volumes/
data/

# IDE
.vscode/
.idea/
""",

    "base": """
# OS files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
*.sublime-*

# Logs
*.log
logs/

# Temporary files
*.tmp
*.temp
*.bak
*.backup
"""
}

COMBINATIONS = {
    "fullstack": ["node", "python", "web"],
    "ml": ["python", "base"],
    "mobile": ["flutter", "base"],
    "devops": ["docker", "base"],
    "game": ["unity", "base"]
}


def list_templates():
    """List all available templates"""
    print("Available templates:")
    print("=" * 40)
    for name in sorted(TEMPLATES.keys()):
        print(f"  {name:15} - {get_template_description(name)}")
    
    print("\nCombinations:")
    print("=" * 40)
    for name, combo in COMBINATIONS.items():
        print(f"  {name:15} - {', '.join(combo)}")


def get_template_description(name):
    """Get description for a template"""
    descriptions = {
        "python": "Python projects",
        "node": "Node.js/JavaScript projects",
        "go": "Go projects",
        "rust": "Rust projects",
        "java": "Java/Maven/Gradle projects",
        "web": "Web development (HTML/CSS/JS)",
        "flutter": "Flutter/Dart projects",
        "unity": "Unity game projects",
        "docker": "Docker/container projects",
        "base": "OS files, IDE configs, logs"
    }
    return descriptions.get(name, "Unknown")


def generate_gitignore(templates, custom_rules=None):
    """Generate .gitignore content from templates"""
    content = ["# Generated by .gitignore Generator"]
    content.append("# https://github.com/yourusername/gitignore-generator")
    content.append("")
    
    seen = set()
    for template_name in templates:
        if template_name in COMBINATIONS:
            # Expand combination
            for sub_template in COMBINATIONS[template_name]:
                if sub_template not in seen:
                    content.append(f"# {sub_template.upper()}")
                    content.append(TEMPLATES.get(sub_template, "").strip())
                    content.append("")
                    seen.add(sub_template)
        else:
            if template_name not in seen:
                content.append(f"# {template_name.upper()}")
                content.append(TEMPLATES.get(template_name, "").strip())
                content.append("")
                seen.add(template_name)
    
    if custom_rules:
        content.append("# Custom rules")
        for rule in custom_rules:
            content.append(rule)
        content.append("")
    
    return "\n".join(content)


def interactive_mode():
    """Interactive mode for selecting templates"""
    print("🎯 .gitignore Generator - Interactive Mode")
    print("=" * 50)
    
    print("\nWhat type of project are you working on?")
    print("(Enter multiple numbers separated by spaces)")
    print()
    
    templates_list = list(TEMPLATES.keys())
    for i, name in enumerate(templates_list, 1):
        print(f"  {i}. {name:15} - {get_template_description(name)}")
    
    print(f"\n  99. Combination presets")
    
    choices = input("\nYour choice(s): ").strip().split()
    
    selected = []
    for choice in choices:
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(templates_list):
                selected.append(templates_list[idx])
        except ValueError:
            pass
    
    if "99" in choices:
        print("\nCombinations:")
        for name, combo in COMBINATIONS.items():
            print(f"  {name}: {', '.join(combo)}")
        combo_choice = input("Choose combination: ").strip()
        if combo_choice in COMBINATIONS:
            selected.append(combo_choice)
    
    custom = input("\nAdd custom rules? (comma-separated, or press Enter to skip): ").strip()
    custom_rules = [r.strip() for r in custom.split(",") if r.strip()] if custom else None
    
    return selected, custom_rules


def main():
    parser = argparse.ArgumentParser(
        description="Generate .